#!/bin/bash
#push pull file
epush="push ip port user password local_file remote_file";
epull="pull ip port user password remote_file local_file";

if [[ "$1" != "push" && "$1" != "pull" ]]; then
  echo -e "use: \n  ${epush}\n  ${epull}"
  exit 1
fi

if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ] && [ ! -z "$4" ] && [ ! -z "$5" ] && [ ! -z "$6" ] && [ ! -z "$7" ]; then
  if [ "$1" == "push" ]; then
    /opt/sh/expect-scp-push.sh $2 $3 $4 $5 $6 $7
  fi
  if [ "$1" == "pull" ]; then
    /opt/sh/expect-scp-pull.sh $2 $3 $4 $5 $6 $7
  fi
fi
